shop/app_user/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView, \
    PasswordResetView
from django.urls import path, reverse_lazy
from django.views.generic import TemplateView, RedirectView
from django.contrib.auth import views as auth_views

from .views import UserLogin, UserLogout, UserRegistration, UserListView, \
    UserProfileUpdateView, CheckEmailExistView, UserFeedbackView, UserVerifyView, UserDetailView, UserActivateView, \
    delete_account, delete_account_confirm, change_password

app_name = 'app_user'

urlpatterns = [
    path('login/', UserLogin.as_view(), name='login'),
    path('logout/', UserLogout.as_view(), name='logout'),
    path('sigh-in/', UserRegistration.as_view(), name='sigh-in'),
    # Активация аккаунта (GET запрос)
    path('activate/<uidb64>/<token>/', UserActivateView.as_view(), name='activate'),

    # Страница подтверждения отправки email
    path('email-confirmation-sent/', TemplateView.as_view(
        template_name='app_user/email_confirmation_sent.html'
    ), name='email_confirmation_sent'),
    path('password_reset/', PasswordResetView.as_view(
        template_name='registration/password_reset_form.html',
        email_template_name='registration/password_reset_email.html',
        success_url=reverse_lazy('app_user:password_reset_done')
    ), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='registration/password_reset_done.html'
    ), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='registration/password_reset_confirm.html',
        success_url=reverse_lazy('app_user:password_reset_complete')
    ), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html'
    ), name='password_reset_complete'),

    path('users/<int:pk>/profile/', UserDetailView.as_view(), name='profile'),
    path('users/<int:pk>/profile/update/', UserProfileUpdateView.as_view(), name='profile-update'),
    path('users/', UserListView.as_view(), name='users'),
    path('users/<int:pk>/verify/', UserVerifyView.as_view(), name='verify'),
    path('users/feedback/', UserFeedbackView.as_view(), name='feedback'),
    path('users/check_email/', CheckEmailExistView.as_view(), name='check-email'),
    path('delete-account/', delete_account, name='delete_account'),
    path('delete-account/confirm/<uidb64>/<token>/', delete_account_confirm, name='delete_account_confirm'),
    path('delete-account/email-sent/', TemplateView.as_view(template_name="registration/delete_account_email_sent.html"),
         name='delete_account_email_sent'),
    path('change-password/', change_password, name='change_password'),

]

shop/shop/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic import RedirectView, TemplateView

urlpatterns = [
    # path('', RedirectView.as_view(url=reverse_lazy("blogs:blogs"), permanent=True)),
    path('admin/', admin.site.urls),
    path('', include('app_user.urls', namespace='app_user')),
    path('', include('app_shop.urls')),
    path("", RedirectView.as_view(url=reverse_lazy("shop:products"))),
] + debug_toolbar_urls()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/app_user/models.py
import datetime
import os
from time import timezone

from django.contrib.auth.models import User, AbstractUser, UserManager
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django.db import models
from django.urls import reverse


class CustomUserManager(UserManager):
    def get_by_natural_key(self, email):
        """Логин по email"""
        return self.get(email__iexact=email)


class SiteUser(AbstractUser):
    """Модель пользователя на сайте"""
    username = None  # <-- полностью отключаем это поле
    email = models.EmailField(unique=True, verbose_name='Email')
    phone_regex = RegexValidator(regex=r'^((\+7)+([0-9]){10})$',
                                 message="Телефонный номер должен быть введен в формате: '+79991234567'.")
    phone_number = models.CharField(verbose_name="Телефон", validators=[phone_regex, ], max_length=12, unique=True)
    address = models.CharField(verbose_name="Адрес доставки", max_length=60)
    registered_at = models.DateTimeField(verbose_name="Дата регистрации", auto_now_add=True)
    verified_at = models.DateTimeField(verbose_name="Дата верификации", null=True, blank=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def get_absolute_url(self):
        return reverse('app_user:user', args=[str(self.user.id)])

    def __str__(self):
        return self.email


class Profile(models.Model):
    """Модель Профиль пользователя, расширяющая модель SiteUser через связь OnrToOne"""

    def create_path(self, filename):
        if self.user.first_name and self.user.last_name:
            user = '_'.join([self.user.first_name, self.user.last_name, 'avatar'])
        else:
            user = '_' + self.user.email.split('@')[0]
        return os.path.sep.join(['users', f'user-id-{self.user.id}', 'avatars', user + ".jpg"])

    def validate_date_in_past(value):
        today = datetime.date.today()
        if value >= today:
            raise ValidationError('Дата рождения должна быть меньше текущей даты')

    user = models.OneToOneField(SiteUser, on_delete=models.CASCADE)
    birthdate = models.DateField(verbose_name="Дата рождения", validators=[validate_date_in_past])
    bio = models.TextField(verbose_name="О себе", max_length=1000, blank=True, null=True)
    avatar = models.ImageField(verbose_name="Аватар пользователя", upload_to=create_path, blank=True)

    objects = models.Manager()

    def __str__(self):
        return f"{self.user.username}"

shop/app_user/views.py
import io

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import PermissionRequiredMixin, UserPassesTestMixin, LoginRequiredMixin
from django.contrib.auth.models import Group, User
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import LoginView, LogoutView
from django.core.files.base import ContentFile, File
from django.core.files.images import get_image_dimensions
from django.core.mail import send_mail
from django.db.models import Count
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.middleware.csrf import get_token
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import View, generic
from PIL import Image

from .forms import UserRegistrationForm, UserProfileForm, UserProfileUpdateForm, FeedbackForm, ChangePasswordForm
from .models import Profile, SiteUser
from app_shop.services.session_cart import merge_session_cart_to_user_cart


class UserLogin(LoginView):
    """Авторизация пользователя"""
    template_name = "app_user/login.html"

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['username'].widget.attrs.update({'class': 'custom-field__input custom-field__input_wide'})
        form.fields['password'].widget.attrs.update({'class': 'custom-field__input custom-field__input_wide'})
        return form

    def form_valid(self, form):
        response = super().form_valid(form)

        # Переносим корзину после успешного входа
        merge_session_cart_to_user_cart(self.request)

        return response


class UserLogout(LogoutView):
    """Выход пользователя из системы"""
    template_name = "app_user/logout.html"


class UserRegistration(View):
    """Регистрация пользователя"""

    @classmethod
    def get(cls, request):
        user_form = UserRegistrationForm()
        profile_form = UserProfileForm()
        context = {
            'forms': [user_form, profile_form]
        }
        return render(request, 'app_user/registration.html', context=context)

    @classmethod
    def post(cls, request):
        user_form = UserRegistrationForm(request.POST)
        profile_form = UserProfileForm(request.POST, request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save(commit=False)
            user.username = user.email
            user.is_active = False  # Аккаунт не активен до подтверждения email
            user.save()
            try:
                default_group = Group.objects.get(name='Обычный пользователь')
            except Group.DoesNotExist:
                user_form.add_error('username', 'Ошибка базы -  группы Обычный пользователь не существует')
                forms = [user_form, profile_form]
                return render(request, 'app_user/registration.html', {'forms': forms})
            if default_group:
                user.groups.add(default_group)
            profile = profile_form.save(commit=False)
            profile.user = user
            image = profile_form.cleaned_data.get('avatar')
            if image:
                file = avatar_resize(image)
                profile.avatar.save(file.name, file)
            profile.save()

            # Генерация токена для подтверждения email
            token = default_token_generator.make_token(user)
            uid = urlsafe_base64_encode(force_bytes(user.pk))
            confirmation_link = request.build_absolute_uri(reverse_lazy('app_user:activate',
                                                                        kwargs={"uidb64": uid, "token": token}))
            print(confirmation_link)
            # Отправка email с подтверждением
            send_mail(
                'Подтверждение регистрации',
                f'Перейдите по ссылке для активации: {confirmation_link}',
                'admin@shop.com',
                [user.email]
            )
            return redirect(reverse_lazy('app_user:email_confirmation_sent'))

            # username = user_form.cleaned_data.get('username')
            # password = user_form.cleaned_data.get('password1')
            # user = authenticate(username=username, password=password)
            # login(request, user)
            # messages.success(request, 'Ваш аккаунт успешно создан. Добро пожаловать.')
            # return redirect(reverse_lazy('app_user:profile', kwargs={'pk': user.id}))
        forms = [user_form, profile_form]
        return render(request, 'app_user/registration.html', {'forms': forms})


def avatar_resize(image):
    """Изменение размеров файла аватара"""
    img_width, img_height = get_image_dimensions(image)
    image_data = Image.open(image)

    if img_height > 100:  # Уменьшаем размер, если высота больше 100px
        new_img_height = 100
        new_img_width = int(new_img_height * img_width / img_height)
        image_data = image_data.resize((new_img_width, new_img_height), Image.LANCZOS)

    output = io.BytesIO()
    image_data.save(output, format="JPEG", optimize=True, quality=75)
    output.seek(0)

    content_file = ContentFile(output.read())  # Создаём файл в памяти
    output.close()

    return File(content_file)


class UserActivateView(View):
    def get(self, request, uidb64, token):
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = SiteUser.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, SiteUser.DoesNotExist):
            user = None

        if user is not None and default_token_generator.check_token(user, token):
            user.is_active = True
            user.verified_at = timezone.now()
            user.save()
            login(request, user)
            return redirect('app_user:profile', pk=user.pk)
        else:
            return render(request, 'app_user/activation_invalid.html')


class UserDetailView(generic.DetailView):
    """Просмотр профиля пользователя"""
    model = SiteUser
    template_name = "app_user/profile.html"
    queryset = SiteUser.objects.select_related("profile").all()


class UserProfileUpdateView(UserPassesTestMixin, View):
    """Редактирование профиля пользователя"""
    # permission_required = 'app_user.change_profile'
    # model = Profile
    # form_class = UserProfileUpdateForm
    # template_name = "users/profile_update.html"

    def test_func(self):
        user = Profile.objects.get(id=self.kwargs.get("pk")).user
        check_status = (self.request.user == user) or \
                       (self.request.user.groups.filter(name__in=['Модератор']).exists())
        return check_status

    @classmethod
    def get(cls, request, *args, **kwargs):
        profile_id = kwargs.get('pk')
        profile = Profile.objects.get(id=profile_id)
        # form = UserProfileUpdateForm(instance=profile)
        form = UserProfileUpdateForm(initial={
            'first_name': profile.user.first_name,
            'last_name': profile.user.last_name,
            'location': profile.location,
            'bio': profile.bio,
        })
        return render(request, 'app_user/profile_update.html', {'form': form, 'profile': profile})

    def post(self, request, *args, **kwargs):
        profile_id = kwargs.get('pk')
        profile = Profile.objects.get(id=profile_id)
        form = UserProfileUpdateForm(request.POST)
        if form.is_valid():
            if form.has_changed():
                profile.location = form.cleaned_data.get('location')
                profile.bio = form.cleaned_data.get('bio')
                profile.user.first_name = form.cleaned_data.get('first_name')
                profile.user.last_name = form.cleaned_data.get('last_name')
                profile.save(update_fields=['location', 'bio'])
                profile.user.save(update_fields=['first_name', 'last_name'])
            return redirect(profile.get_absolute_url())
        return render(request, 'app_user/profile_update.html', {'form': form})


class UserListView(generic.ListView):
    """Списковый просмотр пользователей"""
    model = SiteUser
    template_name = "app_user/user_list.html"
    queryset = SiteUser.objects.select_related("profile").all()


class UserVerifyView(PermissionRequiredMixin, View):
    """Представление перевода пользователя в группу Верифицированные пользователи"""
    # @permission_required('app_user.verify')
    permission_required = 'app_user.verify'

    @classmethod
    def get(cls, request, pk, *args, **kwargs):
        user = User.objects.get(id=pk)
        user_group = Group.objects.get(name='Верифицированный пользователь')
        # user.groups.add(user_group)
        user.groups.set([user_group])

        profile = Profile.objects.get(user=user)
        profile.is_verified = True
        profile.save(update_fields=['is_verified'])

        messages.success(request, f'Пользователь {user.get_full_name()} успешно верифицирован')

        return HttpResponseRedirect(reverse('app_user:user_list'))


class UserFeedbackView(View):
    """Отправка сообщения обратной связи"""

    def get(self, *args, **kwargs):
        if self.request.user.is_anonymous:
            feedback_form = FeedbackForm()
        else:
            feedback_form = FeedbackForm(initial={
                "name": f"{self.request.user.first_name} {self.request.user.last_name}",
                "email": self.request.user.email
            })
        return render(request=self.request, template_name="app_user/feedback.html", context={"form": feedback_form})


    def post(self, *args, **kwargs):

shop/app_user/templates/app_user/activation_invalid.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="alert alert-danger">
        <h4>Ошибка активации</h4>
        <p>Ссылка активации недействительна или устарела.</p>
        <p>Пожалуйста, запросите новую ссылку или обратитесь в поддержку.</p>
        <a href="{% url 'app_user:sigh-in' %}" class="btn btn-primary">Зарегистрироваться снова</a>
    </div>
</div>
{% endblock %}

shop/app_user/templates/app_user/email_confirmation_sent.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="alert alert-danger">
        <h4>Проверьте указанную при регистрации форму</h4>
        <p>Если письмо электронной почты не получено</p>
        <p>Пожалуйста, запросите новую ссылку или обратитесь в поддержку.</p>
        <a href="{% url 'app_user:sigh-in' %}" class="btn btn-primary">Зарегистрироваться снова</a>
    </div>
</div>
{% endblock %}

shop/app_user/templates/app_user/feedback.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Обратная связь{% endblock title %}


{% block css %}
{% endblock css %}


{% block content %}
<section class="user">
    <div class="user__messages" id="messages"></div>
    <div class="user__container container">
        <div class="user__header">
            <h2 class="user__heading">Обратная связь</h2>
        </div>
        <form class="feedback__form form" method="post" action="{% url 'app_user:feedback' %}">
            {% csrf_token %}
            <div class="form__wrapper">
                {% include "widgets/_custom-form.html" %}
            </div>
            <div class="form__btn-block">
                <button class="form__btn btn btn_reset" type="submit">Отправить</button>
            </div>
        </form>
    </div>
</section>
{% endblock content %}


{% block script %}
<script src="{% static 'libs/jquery/jquery-3.6.0.min.js' %}"></script>

<script>
    $(document).ready(function(){
        $('.feedback__form').on('submit', function(event){
            event.preventDefault();
            var formData = $(this).serialize();
            console.log($(this).attr('action'))

            $.ajax({
                url: $(this).attr('action'), 
                type: "POST",
                data: formData,
                success: function(response){
                    $(".feedback__form").trigger("reset");
                    let msg = 
                    `<ul class="messages">
                        <li onclick="this.remove()" class="messages__item message message_success" role="alert">
                            <div class="message__icon" aria-hidden="true"></div>
                            <div class="message__text">${response.message}</div>
                        </li>
                    </ul>`
                    $("#messages").append(msg);
                    setTimeout(function() {
                        window.location.href = response.redirect_url;
                    }, 2000);
                },
                error: function(response){
                    $('.feedback__form .form__wrapper').html(response.responseJSON.form_html);
                }
            });
        });
    });
</script>
{% endblock script %}

shop/app_user/templates/app_user/login.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Страница авторизации{% endblock title %}


{% block css %}
<link href="{% static 'css/app_user/user.css' %}" rel="stylesheet">
{% endblock css %}


{% block content %}
<section class="user">
    <div class="user__container container">
        <div class="user__header">
            <h2 class="user__heading">Страница авторизации</h2>
        </div>
        <form class="form form_reg" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include "widgets/_custom-form.html" %}
            <div class="form__btn-block">
                <button class="form__btn btn btn_reset" type="submit">ok</button>
            </div>
        </form>
        <a href="{% url 'app_user:password_reset' %}">Забыли пароль?</a>
    </div>
</section>
{% endblock content %}


{% block script %}
{% endblock script %}

shop/app_user/templates/app_user/logout.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Профиль пользователя{% endblock title %}


{% block css %}
<link href="{% static 'css/app_user/user.css' %}" rel="stylesheet">
{% endblock css %}


{% block content %}
<section class="user">
    <div class="user__container container">
        <div class="user__header">
            <h2 class="user__heading">Вы успешно вышли</h2>
        </div>
        <span>Для входа в систему нажмите <a href="{% url 'app_user:login' %}">Войти</a>
    </div>
</section>
{% endblock content %}


{% block script %}
{% endblock script %}

shop/app_user/templates/app_user/profile.html
{% extends 'base.html' %}
{% load static %}
{% load users_tag %}


{% block title %}Профиль пользователя {{ user.get_full_name|default:user.username }}{% endblock title %}


{% block css %}
<link href="{% static 'css/app_user/user.css' %}" rel="stylesheet">

{% endblock css %}


{% block content %}
{% for message in messages %}
    <p>{{ message }}</p>
{% endfor %}
<section class="user">
    <div class="user__container container">
        <div class="user__header">
            <h2 class="user__heading">Профиль пользователя {{ user.get_full_name|default:user.email }}</h2>
            {% if "Обычный пользователь" in user.groups.all|join:", " %}
                <span>Ваш аккаунт проходит проверку, после её завершения вы сможете создать блог</span>
            {% endif %}
        </div>
        <div class="user__info">
            <div class="user__avatar-wrapper">
                {% if user.profile.avatar %}
                    <img class="user__avatar" src="{{ user.profile.avatar.url }}" alt="Аватар">
                {% else %}
                    <img class="user__avatar" src="{% static 'imgs.avatar.png' %}" alt="Аватар">
                {% endif %}
            </div>
            <div class="user__details user-details">
                <h3 class="user-details__heading subheadings">Персональная информация</h3>
                <div class="data">
                    <dl class="data__item">
                        <dt class="data__label">Имя пользователя</dt>
                        <dd class="data__value">{{ user.email }} {{ user.is_superuser }}</dd>
                    </dl>
                    <dl class="data__item">
                        <dt class="data__label">Имя</dt>
                        <dd class="data__value">{{ user.first_name }}</dd>
                    </dl>
                    <dl class="data__item">
                        <dt class="data__label">Фамилия</dt>
                        <dd class="data__value">{{ user.last_name }}</dd>
                    </dl>
                    <dl class="data__item">
                        <dt class="data__label">Электронная почта</dt>
                        <dd class="data__value">{{ user.email }}</dd>
                    </dl>
                    <dl class="data__item">
                        <dt class="data__label">Телефон</dt>
                        <dd class="data__value">{{ user.profile.phone }}</dd>
                    </dl>
                    <dl class="data__item">
                        <dt class="data__label">Дата рождения</dt>
                        <dd class="data__value">{{ user.profile.birthdate }}</dd>
                    </dl>
                    <dl class="data__item">
                        <dt class="data__label">Город проживания</dt>
                        <dd class="data__value">{{ user.profile.location }}</dd>
                    </dl>
                    <dl class="data__item">
                        <dt class="data__label">О себе</dt>
                        <dd class="data__value">{{ user.profile.bio|default:"Тайна" }}</dd>
                    </dl>
                    <dl class="data__item">
                        <dt class="data__label">Верифицирован</dt>
                        <dd class="data__value">{% if user.profile.is_verified == True %}Да{% else %}Нет{% endif %}</dd>
                    </dl>
                    <dl class="data__item">
                        <dt class="data__label">Роль</dt>
                        <dd class="data__value">
                            {% for group in user.groups.all %}
                                <p>{{ group.name }}</p>
                            {% endfor %}
                        </dd>
                    </dl>
                </div>
                <div class="btns">
                    <a class="user__delete-account btn btn_reset btn_simple" href="{% url 'app_user:delete_account' %}">Удалить аккаунт</a>
                    <a class="user__delete-account btn btn_reset btn_simple" href="{% url 'app_user:change_password' %}">Сменить пароль</a>
                </div>
            </div>
        </div>
        <div class="user__blogs user-blogs">
            <h3>История заказов</h3>
            <ul>
            {% for order in orders %}
                <li>Заказ #{{ order.id }} - Создан: {{ order.created_at }}</li>
            {% empty %}
                <li>Заказов пока нет</li>
            {% endfor %}
            </ul>
            <a href="{% url 'app_user:delete_account' %}">Удалить аккаунт</a>
        </div>
    </div>
</section>
{% endblock content %}


{% block script %}
{% endblock script %}

shop/app_user/templates/app_user/profile_update.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Профиль пользователя{% endblock title %}


{% block css %}
{% endblock css %}


{% block content %}
<section class="user">
    <div class="user__container container">
        <div class="user__header">
            <h2 class="user__heading">Профиль пользователя</h2>
        </div>
        <form class="registration__form form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include "widgets/_custom-form.html" %}
            <div class="form__btn-block">
                <button class="form__btn btn btn_reset" type="submit">Сохранить</button>
            </div>
        </form>
    </div>
</section>
{% endblock content %}


{% block script %}
{% endblock script %}

shop/app_user/templates/app_user/registration.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Регистрация{% endblock title %}


{% block css %}
<link href="{% static 'app_user/css/users.css' %}" rel="stylesheet">
{% endblock css %}


{% block content %}
<section class="user">
    <div class="user__container container">
        <div class="user__header">
            <h2 class="user__heading">Регистрация</h2>
        </div>
        <form class="registration__form form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for form in forms %}
                {% include "widgets/_custom-form.html" %}
            {% endfor %}
            <div class="form__btn-block">
                <button class="form__btn btn btn_reset" type="submit">Зарегистрироваться</button>
            </div>
        </form>
    </div>
</section>
{% endblock content %}

{% block script %}
<script src="{% static 'libs/jquery/jquery-3.6.0.min.js' %}"></script>

<script>
$(document).ready(function () {
    $("#id_email").on("blur", function () {
        let email = $(this).val().trim();  // Берём введённый email
        if (!email) return;  // Если поле пустое — ничего не делаем

        if (!validateEmail(email)) {  // Проверяем, корректный ли email
            showMessage("Введите корректный email");
            return;
        } else {
            $("#id_email").parent().find(".custom-field__error-message").remove();
        };

        $.ajax({
            url: "{% url 'app_user:check-email' %}",  // URL эндпоинта проверки email
            type: "GET",
            data: { email: email },
            success: function (response) {
                console.log(response)
                if (response.available) {
                    $("#id_email").parent().find(".custom-field__error-message").remove();
                } else {
                    showMessage("Этот email уже занят",);
                };
            },
            error: function () {
                showMessage("Ошибка проверки email",);
            }
        });
    });

    function validateEmail(email) {
        let re = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;
        return re.test(email);
    }

    function showMessage(message) {
        let msg = `<span class="custom-field__error-message" aria-live="polite">${message}</span>`;
        $("#id_email").parent().append(msg);

        setTimeout(function () {
            $("#id_email").parent().find(".custom-field__error-message").fadeOut();
        }, 5000);
    }
});
</script>
{% endblock script %}

shop/app_user/templates/app_user/user_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Список пользователей{% endblock title %}
{% block css %}
{% endblock css %}
{% block content %}
<h1>Список пользователей</h1>

{% for message in messages %}
    <p>{{ message }}</p>
{% endfor %}

<table>
    <tr>
        <td>Имя</td><td>Фамилия</td>
        <td>Электронная почта</td>
        <td>Телефон</td>
        <td>Дата рождения</td>
        <td>Город проживания</td>
        <td>Верифицирован</td>
        <td>Роль</td>
    </tr>
{%  for user in user_list %}
     <tr>
         <td><a href="{{ user.profile.get_absolute_url }}">{{ user.first_name }}</a></td>
        <td>{{ user.last_name }}</td>
         <td>{{ user.email }}</td>
         <td>{{ user.profile.phone }}</td>
         <td>{{ user.profile.birthdate }}</td>
         <td>{{ user.profile.location }}</td>
         <td>{% if user.profile.is_verified == True %}Да{% else %}Нет{% endif %}</td>
         <td>{% for group in user.groups.all %}
            <span>{{ group.name }} </span>
            {% endfor %}
        </td>
         <td>
             {% if user.profile.is_verified != True %}
             <a class="btn" href="{% url 'app_user:verify' user.id %}">Верифицировать</a> {{ perms.app_user.verify }}
             {% endif %}
         </td>
    </tr>
{% endfor %}


</table>
{% endblock content %}

{% block script %}
{% endblock script %}