shop/app_shop/urls.py
from django.urls import path

from .views import product_detail, product_list, ProductListView, ProductDetailView, cart_view, add_to_cart, \
    remove_from_cart, ProductCreateView, ProductUpdateView, ProductDeleteView, ProductImageDeleteView, \
    CategoryCreateView, CategoryUpdateView, CategoryDeleteView, CategoryDetailView, CategoryListView, \
    ProductSetCategoryView, ProductJsonSearchView

app_name = "shop"

urlpatterns = [
    # path("products/<int:pk>", ProductDetailView.as_view(), name="product-detail"),
    path("products/<int:pk>", product_detail, name="product-detail"),
    # path("products/", ProductListView.as_view(), name="products"),
    path("products/", product_list, name="products"),
    path("products/create", ProductCreateView.as_view(), name="product-create"),
    path("products/<int:pk>/update", ProductUpdateView.as_view(), name="product-update"),
    path("products/<int:pk>/delete", ProductDeleteView.as_view(), name="product-delete"),
    path("products/product-image/<int:pk>/delete", ProductImageDeleteView.as_view(), name="product-image-delete"),
    path("product/<int:product_pk>/set-category/<int:category_pk>", ProductSetCategoryView.as_view(),
         name="product-set-category"),
    path("product/json-search", ProductJsonSearchView.as_view(),
         name="product-json-search"),

    path("category/", CategoryListView.as_view(), name="category-list"),
    path("category/<int:pk>", CategoryDetailView.as_view(), name="category-detail"),
    path("category/create", CategoryCreateView.as_view(), name="category-create"),
    path("category/<int:pk>/update", CategoryUpdateView.as_view(), name="category-update"),
    path("category/<int:pk>/delete", CategoryDeleteView.as_view(), name="category-delete"),

    path('cart/', cart_view, name='cart_view'),
    path('add-to-cart/<int:product_id>/<int:quantity>', add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<int:product_id>/', remove_from_cart, name='remove_from_cart'),
]

shop/app_user/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView, \
    PasswordResetView
from django.urls import path, reverse_lazy
from django.views.generic import TemplateView, RedirectView
from django.contrib.auth import views as auth_views

from .views import UserLogin, UserLogout, UserRegistration, UserListView, \
    UserProfileUpdateView, CheckEmailExistView, UserFeedbackView, UserVerifyView, UserDetailView, UserActivateView, \
    delete_account, delete_account_confirm, change_password

app_name = 'app_user'

urlpatterns = [
    path('login/', UserLogin.as_view(), name='login'),
    path('logout/', UserLogout.as_view(), name='logout'),
    path('sigh-in/', UserRegistration.as_view(), name='sigh-in'),
    # Активация аккаунта (GET запрос)
    path('activate/<uidb64>/<token>/', UserActivateView.as_view(), name='activate'),

    # Страница подтверждения отправки email
    path('email-confirmation-sent/', TemplateView.as_view(
        template_name='app_user/email_confirmation_sent.html'
    ), name='email_confirmation_sent'),
    path('password_reset/', PasswordResetView.as_view(
        template_name='registration/password_reset_form.html',
        email_template_name='registration/password_reset_email.html',
        success_url=reverse_lazy('app_user:password_reset_done')
    ), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='registration/password_reset_done.html'
    ), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='registration/password_reset_confirm.html',
        success_url=reverse_lazy('app_user:password_reset_complete')
    ), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html'
    ), name='password_reset_complete'),

    path('users/<int:pk>/profile/', UserDetailView.as_view(), name='profile'),
    path('users/<int:pk>/profile/update/', UserProfileUpdateView.as_view(), name='profile-update'),
    path('users/', UserListView.as_view(), name='users'),
    path('users/<int:pk>/verify/', UserVerifyView.as_view(), name='verify'),
    path('users/feedback/', UserFeedbackView.as_view(), name='feedback'),
    path('users/check_email/', CheckEmailExistView.as_view(), name='check-email'),
    path('delete-account/', delete_account, name='delete_account'),
    path('delete-account/confirm/<uidb64>/<token>/', delete_account_confirm, name='delete_account_confirm'),
    path('delete-account/email-sent/', TemplateView.as_view(template_name="registration/delete_account_email_sent.html"),
         name='delete_account_email_sent'),
    path('change-password/', change_password, name='change_password'),

]

shop/shop/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic import RedirectView, TemplateView

urlpatterns = [
    # path('', RedirectView.as_view(url=reverse_lazy("blogs:blogs"), permanent=True)),
    path('admin/', admin.site.urls),
    path('', include('app_user.urls', namespace='app_user')),
    path('', include('app_shop.urls')),
    path("", RedirectView.as_view(url=reverse_lazy("shop:products"))),
] + debug_toolbar_urls()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/app_shop/models.py
import os

from django.core.validators import MinValueValidator
from django.db import models
from django.db.models.signals import pre_delete
from django.dispatch import receiver
from django.urls import reverse
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel

from app_user.models import SiteUser


class Category(MPTTModel):
    """Модель Категория"""
    name = models.CharField(verbose_name="название", max_length=100)
    parent = TreeForeignKey('self', verbose_name="головная категория",
                            on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    deleted_at = models.DateTimeField(verbose_name="дата удаления", blank=True, null=True)

    class MPTTMeta:
        order_insertion_by = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("shop:category-detail", args=(self.pk, ))


class Product(models.Model):
    """Модель Товара"""
    category = models.ForeignKey("Category", verbose_name="категория", on_delete=models.CASCADE)
    name = models.CharField(verbose_name="название", max_length=200, unique=True)
    description = models.TextField(verbose_name="описание")
    price = models.DecimalField(verbose_name="цена", max_digits=10, decimal_places=2,
                                validators=[MinValueValidator(0)])
    draft = models.BooleanField(verbose_name="удален", default=False)
    author = models.ForeignKey(SiteUser, verbose_name="создал/изменил", on_delete=models.PROTECT)
    created_at = models.DateTimeField(verbose_name="дата создания", auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name="дата редактирования", auto_now=True)
    deleted_at = models.DateTimeField(verbose_name="дата удаления", blank=True, null=True)

    objects = models.Manager()

    class Meta:
        verbose_name = "товар"
        verbose_name_plural = "товары"
        ordering = ["name", "-created_at", "-updated_at", ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product-detail', args=[str(self.id)])


class ProductImage(models.Model):
    """Модель изображения Товара :model:'app_shop:Product'"""

    def image_path(self, filename):
        return os.path.join('products', 'images', str(self.product.id), filename)

    product = models.ForeignKey(Product, verbose_name="товар", on_delete=models.CASCADE)
    file = models.ImageField(verbose_name="изображения", upload_to=image_path)
    author = models.ForeignKey(SiteUser, verbose_name="создал/изменил", on_delete=models.PROTECT)
    created_at = models.DateTimeField(verbose_name="дата создания", auto_now_add=True)

    objects = models.Manager()

    class Meta:
        verbose_name = "изображение товара"
        verbose_name_plural = "изображения товаров"
        ordering = ["-created_at", ]

    def __str__(self):
        return f"ProductImage({self.file.name}) for Product(id={self.product.pk}, name={self.product.name})"


@receiver(pre_delete, sender=ProductImage)
def image_model_delete(sender, instance, **kwargs):
    """Физическое удаление файлов при удалении экземпляра модели"""
    if instance.file.name:
        instance.file.delete(False)


class Cart(models.Model):
    """Модель корзины Пользователя"""
    user = models.OneToOneField(SiteUser, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    objects = models.Manager()


class CartItem(models.Model):
    """Модель позиция товара в Корзине :model:'app_shop.Cart'"""
    cart = models.ForeignKey(Cart, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    objects = models.Manager()


class Order(models.Model):
    """Модель заказа"""
    user = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Заказ {self.id} от {self.user}"


class OrderItem(models.Model):
    """Модель Позиция в заказе"""
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} x {self.product.name}"

shop/templates/include/nav.html
<nav class="nav">
    <div class="nav__container container">
        <ul class="nav__list ">
            <li class="nav__item">
                <a href="{% url 'app_user:feedback' %}" class="nav__link">Обратная связь</a>
            </li>
            <li class="nav__item">
                <a href="{% url 'shop:products' %}" class="nav__link">Товары</a>
            </li>
            <li class="nav__item">
                <a href="{% url 'shop:cart_view' %}" class="nav__link">Корзина</a>
            </li>
            {% if request.user.is_authenticated %}
                <li class="nav__item">
                    <a class="nav__link" href="{% url 'app_user:profile'  request.user.pk%}">Личный кабинет</a>
                </li>
                <li class="nav__item">
                    <form action="{% url 'app_user:logout'%}" method="POST">
                        {% csrf_token %}
                        <button class="nav__link" type="submit">Выйти</button>
                    </form>
                </li>
                {% if perms.app_shop.add_category %}
                    <a class="nav__link" href="{% url 'shop:category-create' %}">Новая категория</a>
                {% endif %}
            {% else %}
            <li class="nav__item">
                <a class="nav__link" href="{% url 'app_user:login' %}?next={{request.path}}">Войти</a>
            </li>
            <li class="nav__item">
                <a class="nav__link" href="{% url 'app_user:sigh-in' %}">Зарегистрироваться</a>
            </li>
            {% endif %}
        </ul>
        {% if not request.user.is_authenticated %}
            <span class="nav__info">Для доступа к полному функционалу необходим вход в систему.</span>
        {% endif %}
        <div class="cart-info">
            <a href="{% url 'shop:cart_view' %}"> Корзина
                <p>Товаров в корзине: <span id="total_quantity">{{ context_cart.total_quantity|default:"0" }}</span></p>
                <p>Сумма: <span id="total_price">{{ context_cart.total_price|default:"0"|floatformat:2 }}</span></p>
            </a>
        </div>
    </div>
</nav>

shop/templates/include/pagination.html
{% if is_paginated %}
    <ul class="pagination">
        {% if page_obj.has_previous %}
            {% if page_obj.number|add:'-3' > 1 %}
                <li class="pagination__item">
                    <a class="pagination__link" href="?{{ paginator_query }}{{ search_string }}{{ search_type }}{{ filter }}{{ object }}page=1">1</a>
                </li>
            {% endif %}
            {% if page_obj.number|add:'-3' >= 3 %}
                <li class="pagination__item pagination__item--dots">
                        <a class="pagination__link" href="?{{ paginator_query }}{{ search_string }}{{ search_type }}{{ filter }}{{ object }}page={{ page_obj.previous_page_number|add:'-3' }}">
                    <span>• • •</span>
                    </a>
                </li>
            {% endif %}
        {% endif %}
        {% if paginator.page_range|length > 1 %}
            {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="pagination__item active">
                        <a class="pagination__link" href="#">{{ i }}</a>
                    </li>
                {% elif i > page_obj.number|add:'-4' and i < page_obj.number|add:'4' %}
                    <li class="pagination__item">
                            <a class="pagination__link" href="?{{ paginator_query }}{{ search_string }}{{ search_type }}{{ filter }}{{ object }}page={{ i }}">{{ i }}</a>
                    </li>
                {% endif %}
            {% endfor %}
        {% endif %}
        {% if page_obj.has_next %}
            {% if page_obj.number|add:'4' < page_obj.paginator.num_pages %}
                <li class="pagination__item pagination__item--dots">
                    <a class="pagination__link" href="?{{ paginator_query }}{{ search_string }}{{ search_type }}{{ filter }}{{ object }}page={{ page_obj.next_page_number|add:'3' }}">
                        <span>• • •</span>
                    </a>
                </li>
            {% endif %}
            {% if page_obj.number|add:'3' < page_obj.paginator.num_pages %}
                <li class="pagination__item">
                    <a class="pagination__link" href="?{{ paginator_query }}{{ search_string }}{{ search_type }}{{ filter }}{{ object }}page={{ page_obj.paginator.num_pages }}">
                        {{ page_obj.paginator.num_pages }}
                    </a>
                </li>
            {% endif %}
        {% endif %}
    </ul>
{% endif %}